### ISSUE TITLE
Getting 500 Error

### ISSUE THREAD

**Issue by flrrrhoffpauir** [nova-framework/framework#2061]
I have a site that has been running on the nova framework 3.78.20 for a while just fine. I keep all of the updates in github, and today I had to download a zip from an older commit and now after running `composer install` I get a 500 error in chrome and I see this error in the php error logs:

```
[27-Mar-2018 15:25:09 America/Chicago] PHP Fatal error:  Uncaught Nova\Container\BindingResolutionException: Target [Nova\Foundation\Contracts\ExceptionHandlerInterface] is not instantiable. in /Applications/MAMP/htdocs/fb_test/fb/vendor/nova-framework/system/src/Container/Container.php:626
Stack trace:
#0 /Applications/MAMP/htdocs/fb_test/fb/vendor/nova-framework/system/src/Container/Container.php(548): Nova\Container\Container->build('Nova\\Foundation...', Array)
#1 /Applications/MAMP/htdocs/fb_test/fb/vendor/nova-framework/system/src/Foundation/Application.php(459): Nova\Container\Container->make('Nova\\Foundation...', Array)
#2 /Applications/MAMP/htdocs/fb_test/fb/vendor/nova-framework/system/src/Exception/Handler.php(190): Nova\Foundation\Application->make('Nova\\Foundation...')
#3 /Applications/MAMP/htdocs/fb_test/fb/vendor/nova-framework/system/src/Exception/Handler.php(100): Nova\Exception\Handler->getExceptionHandler()
#4 /Applications/MAMP/htdocs/fb_test/fb/vendor/nova-framework/system/src/Exception/Handler.php(117): Nova\Exception\Handler->handleExceptio in /Applications/MAMP/htdocs/fb_test/fb/vendor/nova-framework/system/src/Container/Container.php on line 626
```

**Comment by LuckyCyborg** [comment]
Most likely the error happens because the composer got an Kernel from the current **4.0.x** series.

You have to stuck in a compatible kernel (system), editing in `composer.json` like
```json
"nova-framework/system": "3.78.*",
```
instead of 
```json
"nova-framework/system": "^3.0",
```
Anyway, bear in mind that the application and the kernel should match always.

**Comment by flrrrhoffpauir** [comment]
Ah yes, that did the trick. Thank you!
