### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by amiroperator** [nova-framework/framework#848]
I have an error when I opened profile page:

Exception information:
```

           Date: May 19, 2016 18:16PM

           Message: Class 'MessageFormatter' not found

           Code: 0

           File: E:\Amir\Projects\nova\system\Core\Language.php

           Line: 164

           Stack trace:

           #0 E:\Amir\Projects\nova\system\functions.php(86): Core\Language->translate('\xD9\xBE\xD8\xB1\xD9\x88\xD9\x81\xD8\xA7\xDB\x8C\xD9\x84 ...', Array)
#1 E:\Amir\Projects\nova\app\Modules\Users\Views\Users\Profile.php(2): __d('users', 'User Profile : ...', 'Administrator')
#2 E:\Amir\Projects\nova\system\Core\Base\View.php(91): require('E:\\Amir\\Project...')
#3 E:\Amir\Projects\nova\system\Core\Base\View.php(65): Core\Base\View->render()
#4 [internal function]: Core\Base\View->fetch()
#5 E:\Amir\Projects\nova\system\Core\Base\View.php(325): call_user_func_array(Array, Array)
#6 E:\Amir\Projects\nova\system\Core\Controller.php(127): Core\Base\View->__call('fetch', Array)
#7 E:\Amir\Projects\nova\system\Core\Controller.php(88): Core\Controller->after(Object(Core\View))
#8 E:\Amir\Projects\nova\system\Core\Base\Router.php(187): Core\Controller->execute('profile', Array)
#9 E:\Amir\Projects\nova\system\Core\Base\Router.php(218): Core\Base\Router->invokeController('App\\Modules\\Use...', 'profile', Array)
#10 E:\Amir\Projects\nova\system\Core\Router.php(260): Core\Base\Router->invokeObject('App\\Modules\\Use...', Array)
#11 E:\Amir\Projects\nova\system\bootstrap.php(61): Core\Router->dispatch()
#12 E:\Amir\Projects\nova\public\index.php(68): require('E:\\Amir\\Project...')
#13 {main}

           ---------
```

**Comment by LuckyCyborg** [comment]
You have the PHP **INTL** extension loaded?

This extension is needed for properly work of new Language API

**Comment by amiroperator** [comment]
No I didn't know that
Thanks

**Comment by LuckyCyborg** [comment]
@amiroperator 

> No I didn't know that

I said into Release Notes that the thing is built on top of PHP's **INTL**.

**Comment by amiroperator** [comment]
@LuckyCyborg I didn't pay attention
